"""
This module defines personal shortcut URLs for the Luna Voice Assistant.
These shortcuts map user-friendly keys to specific web addresses or search queries.
"""

# This dictionary maps user phrases to specific commands, including placeholders.
# The keys are patterns that the user might say, and the values are the corresponding shell commands.
# For patterns with placeholders like '{query}', the value will be a format string.
PERSONAL_SHORTCUTS = {
    "ytm: hyperpop": "firefox 'https://music.youtube.com/search?q=hyperpop'",
    "ytm: glitchcore": "firefox 'https://music.youtube.com/search?q=glitchcore'",
    "ytm: ado": "firefox 'https://music.youtube.com/search?q=Ado'",
    "ytm: anisong": "firefox 'https://music.youtube.com/search?q=anisong'",
    "ytm: jpop": "firefox 'https://music.youtube.com/search?q=j-pop'",
    "ytm: phonk": "firefox 'https://music.youtube.com/search?q=phonk'",
    "ytm: brazilian funk": "firefox 'https://music.youtube.com/search?q=brazilian%20funk'",
    "ytm: dark ambient": "firefox 'https://music.youtube.com/search?q=dark%20ambient'",
    "ytm: nu metal": "firefox 'https://music.youtube.com/search?q=nu%20metal'",
    "ytm: industrial rap": "firefox 'https://music.youtube.com/search?q=industrial%20rap'",
    "ytm: vocaloid": "firefox 'https://music.youtube.com/search?q=vocaloid'",
    "ytm: utaite": "firefox 'https://music.youtube.com/search?q=utaite'",
    "youtube music home": "firefox 'https://music.youtube.com'",
    "spotify search": "firefox 'https://open.spotify.com/search'",
    "soundcloud search": "firefox 'https://soundcloud.com/search'",
    "bandcamp discover": "firefox 'https://bandcamp.com/discover'",
    "anime: evangelion": "firefox 'https://myanimelist.net/anime/30/Neon_Genesis_Evangelion'",
    "anime: code geass": "firefox 'https://myanimelist.net/anime/1575/Code_Geass_Hangyaku_no_Lelouch'",
    "anime: overlord": "firefox 'https://myanimelist.net/anime/29803/Overlord'",
    "anime: konosuba": "firefox 'https://myanimelist.net/anime/30831/Kono_Subarashii_Sekai_ni_Shukufuku_wo'",
    "anime: sao": "firefox 'https://myanimelist.net/anime/11757/Sword_Art_Online'",
    "anime: no game no life": "firefox 'https://myanimelist.net/anime/19815/No_Game_No_Life'",
    "anime news": "firefox 'https://www.animenewsnetwork.com/'",
    "crunchyroll search": "firefox 'https://www.crunchyroll.com/search'",
    "bilibili/bstation id": "firefox 'https://www.bilibili.tv/id'",
    "arch wiki home": "firefox 'https://wiki.archlinux.org/'",
    "arch wiki nvidia": "firefox 'https://wiki.archlinux.org/title/NVIDIA'",
    "arch wiki intel graphics": "firefox 'https://wiki.archlinux.org/title/Intel_graphics'",
    "arch wiki swap": "firefox 'https://wiki.archlinux.org/title/Swap'",
    "endeavouros wiki": "firefox 'https://discovery.endeavouros.com/'",
    "kde docs": "firefox 'https://userbase.kde.org/'",
    "hyprland wiki": "firefox 'https://wiki.hyprland.org/'",
    "aur home": "firefox 'https://aur.archlinux.org/'",
    "aur: cursor-bin": "firefox 'https://aur.archlinux.org/packages/cursor-bin'",
    "aur: nvm": "firefox 'https://aur.archlinux.org/packages/nvm'",
    "kvantum github": "firefox 'https://github.com/tsujan/Kvantum'",
    "konsave github": "firefox 'https://github.com/Prayag2/konsave'",
    "nobara project": "firefox 'https://nobaraproject.org/'",
    "pikaos": "firefox 'https://pikaos.com/'",
    "cachyos": "firefox 'https://cachyos.org/'",
    "pop os": "firefox 'https://pop.system76.com/'",
    "kubuntu": "firefox 'https://kubuntu.org/'",
    "github afif": "firefox 'https://github.com/fradana'",
    "repo: personal-dual-de-ricing-endeavouros": "firefox 'https://github.com/fradana/personal-dual-de-ricing-endeavouros'",
    "repo: dotfile": "firefox 'https://github.com/fradana/dotfile'",
    "repo: health-check": "firefox 'https://github.com/fradana/health-check'",
    "github new repo": "firefox 'https://github.com/new'",
    "vscode download": "firefox 'https://code.visualstudio.com/download'",
    "cursor download": "firefox 'https://www.cursor.com/'",
    "cline extension": "firefox 'https://marketplace.visualstudio.com/items?itemName=saoudrizwan.claude-dev'",
    "nodejs download": "firefox 'https://nodejs.org/en/download'",
    "nvm docs": "firefox 'https://github.com/nvm-sh/nvm'",
    "python docs": "firefox 'https://docs.python.org/3/'",
    "pipy search": "firefox 'https://pypi.org/search/'",
    "arch pkg search": "firefox 'https://archlinux.org/packages/'",
    "regex101": "firefox 'https://regex101.com/'",
    "devdocs": "firefox 'https://devdocs.io/'",
    "ollama home": "firefox 'https://ollama.com/'",
    "ollama models": "firefox 'https://ollama.com/library'",
    "gemma models": "firefox 'https://ai.google.dev/gemma'",
    "deepseek coder": "firefox 'https://github.com/deepseek-ai/DeepSeek-Coder'",
    "openrouter models": "firefox 'https://openrouter.ai/models'",
    "gemini api docs": "firefox 'https://ai.google.dev/gemini-api'",
    "gemini cli github": "firefox 'https://github.com/google-gemini/gemini-cli'",
    "nuitka": "firefox 'https://nuitka.net/'",
    "pyinstaller": "firefox 'https://pyinstaller.org/en/stable/'",
    "coqui tts": "firefox 'https://coqui.ai/'",
    "faster-whisper": "firefox 'https://github.com/SYSTRAN/faster-whisper'",
    "whisper cpp": "firefox 'https://github.com/ggerganov/whisper.cpp'",
    "piper tts": "firefox 'https://github.com/rhasspy/piper'",
    "voice activity detection": "firefox 'https://github.com/snakers4/silero-vad'",
    "roblox studio hub": "firefox 'https://create.roblox.com/'",
    "roblox terrain docs": "firefox 'https://create.roblox.com/docs/en-us/resources/terrain'",
    "blender download": "firefox 'https://www.blender.org/download/'",
    "unity download": "firefox 'https://unity.com/download'",
    "travellers rest steam": "firefox 'https://store.steampowered.com/app/1139980/Travellers_Rest/'",
    "travellers rest wiki": "firefox 'https://travellersrest.fandom.com/wiki/Travellers_Rest_Wiki'",
    "moeru ai airi github": "firefox 'https://github.com/moeru-ai/airi'",
    "snapseed tips": "firefox 'https://support.google.com/photos/answer/6128850'",
    "color grading basics": "firefox 'https://blog.photowhoa.com/color-grading-photography/'",
    "histogram tutorial": "firefox 'https://photographylife.com/what-is-histogram-in-photography'",
    "cefiro a31 drift youtube": "firefox 'https://www.youtube.com/results?search_query=cefiro+a31+drift+build'",
    "toyota ke70 drift youtube": "firefox 'https://www.youtube.com/results?search_query=toyota+ke70+drift+build'",
    "jdm marketplace search": "firefox 'https://www.facebook.com/marketplace/?query=cefiro%20a31'",
    "speedhunters": "firefox 'https://www.speedhunters.com/tag/drift/'",
    "leopard gecko care guide": "firefox 'https://reptifiles.com/leopard-gecko-care/'",
    "leopard gecko enclosure ideas": "firefox 'https://www.youtube.com/results?search_query=leopard+gecko+enclosure+setup'",
    "ide tanaman indoor": "firefox 'https://www.youtube.com/results?search_query=indoor+plants+beginner'",
    "ums website": "firefox 'https://www.ums.ac.id/'",
    "akuntansi dasar": "firefox 'https://en.wikipedia.org/wiki/Financial_accounting'",
    "ifrs foundation": "firefox 'https://www.ifrs.org/'",
    "accountingtools": "firefox 'https://www.accountingtools.com/'",
    "kompas": "firefox 'https://www.kompas.com/'",
    "detik": "firefox 'https://www.detik.com/'",
    "the verge": "firefox 'https://www.theverge.com/'",
    "hacker news": "firefox 'https://news.ycombinator.com/'",
    "phind": "firefox 'https://www.phind.com/'",
    "youtube home": "firefox 'https://www.youtube.com/'",
    "youtube search": "firefox 'https://www.youtube.com/results?search_query='",
    "reddit r/linux": "firefox 'https://www.reddit.com/r/linux/'",
    "reddit r/archlinux": "firefox 'https://www.reddit.com/r/archlinux/'",
    "reddit r/unixporn": "firefox 'https://www.reddit.com/r/unixporn/'",
    "twitter/x": "firefox 'https://x.com/'",
    "gmail": "firefox 'https://mail.google.com/'",
    "drive": "firefox 'https://drive.google.com/'",
    "chatgpt": "firefox 'https://chat.openai.com/'",
    "google: {query}": "firefox 'https://www.google.com/search?q={query}'",
    "ytm search: {query}": "firefox 'https://music.youtube.com/search?q={query}'",
    "yt search: {query}": "firefox 'https://www.youtube.com/results?search_query={query}'",
    "github search: {query}": "firefox 'https://github.com/search?q={query}'",
    "aur search: {pkg}": "firefox 'https://aur.archlinux.org/packages?O=0&K={pkg}'",
    "arch wiki search: {term}": "firefox 'https://wiki.archlinux.org/index.php?search={term}'",
}
